// wrapping for uv_wrap generated by swiglite-lua.

#include <lua.h>
#include <lualib.h>
#include <lauxlib.h>

#include "uv.h"

int wrap_uv_accept(lua_State *L) {
    uv_stream_t * server;
    uv_stream_t * *server_p =
        luaL_checkudata(L, 1, "uv_stream_t_ptr");
    server = *server_p;
    printf("  wrap_uv_accept.server: %p\n", server);

    uv_stream_t * client;
    uv_stream_t * *client_p =
        luaL_checkudata(L, 2, "uv_stream_t_ptr");
    client = *client_p;
    printf("  wrap_uv_accept.client: %p\n", client);

    int res = (int)
        uv_accept(server, client);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_ares_destroy(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_ares_destroy.arg_0: %p\n", arg_0);

    ares_channel channel;
    ares_channel *channel_p =
        luaL_checkudata(L, 2, "ares_channel");
    channel = *channel_p;

    uv_ares_destroy(arg_0, channel);
    return 0;
}
int wrap_uv_ares_init_options(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_ares_init_options.arg_0: %p\n", arg_0);

    ares_channel * channelptr;
    ares_channel * *channelptr_p =
        luaL_checkudata(L, 2, "ares_channel_ptr");
    channelptr = *channelptr_p;
    printf("  wrap_uv_ares_init_options.channelptr: %p\n", channelptr);

    struct ares_options * options;
    struct ares_options * *options_p =
        luaL_checkudata(L, 3, "ares_options_ptr");
    options = *options_p;
    printf("  wrap_uv_ares_init_options.options: %p\n", options);

    int optmask;
    optmask = (int) luaL_checkint(L, 4);

    int res = (int)
        uv_ares_init_options(arg_0, channelptr, options, optmask);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_async_init(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_async_init.arg_0: %p\n", arg_0);

    uv_async_t * async;
    uv_async_t * *async_p =
        luaL_checkudata(L, 2, "uv_async_t_ptr");
    async = *async_p;
    printf("  wrap_uv_async_init.async: %p\n", async);

    uv_async_cb async_cb;
    uv_async_cb *async_cb_p =
        luaL_checkudata(L, 3, "uv_async_cb");
    async_cb = *async_cb_p;

    int res = (int)
        uv_async_init(arg_0, async, async_cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_async_send(lua_State *L) {
    uv_async_t * async;
    uv_async_t * *async_p =
        luaL_checkudata(L, 1, "uv_async_t_ptr");
    async = *async_p;
    printf("  wrap_uv_async_send.async: %p\n", async);

    int res = (int)
        uv_async_send(async);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_buf_init(lua_State *L) {
    char * base;
    base = (char *) luaL_checkstring(L, 1);

    size_t len;
    len = (size_t) luaL_checklong(L, 2);

    uv_buf_t res = (uv_buf_t)
        uv_buf_init(base, len);
    uv_buf_t *res_ud =
        lua_newuserdata(L, sizeof(uv_buf_t));
    if (res_ud != NULL) {
        *res_ud = res;

        luaL_newmetatable(L, "uv_buf_t");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int wrap_uv_check_init(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_check_init.arg_0: %p\n", arg_0);

    uv_check_t * check;
    uv_check_t * *check_p =
        luaL_checkudata(L, 2, "uv_check_t_ptr");
    check = *check_p;
    printf("  wrap_uv_check_init.check: %p\n", check);

    int res = (int)
        uv_check_init(arg_0, check);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_check_start(lua_State *L) {
    uv_check_t * check;
    uv_check_t * *check_p =
        luaL_checkudata(L, 1, "uv_check_t_ptr");
    check = *check_p;
    printf("  wrap_uv_check_start.check: %p\n", check);

    uv_check_cb cb;
    uv_check_cb *cb_p =
        luaL_checkudata(L, 2, "uv_check_cb");
    cb = *cb_p;

    int res = (int)
        uv_check_start(check, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_check_stop(lua_State *L) {
    uv_check_t * check;
    uv_check_t * *check_p =
        luaL_checkudata(L, 1, "uv_check_t_ptr");
    check = *check_p;
    printf("  wrap_uv_check_stop.check: %p\n", check);

    int res = (int)
        uv_check_stop(check);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_close(lua_State *L) {
    uv_handle_t * handle;
    uv_handle_t * *handle_p =
        luaL_checkudata(L, 1, "uv_handle_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_close.handle: %p\n", handle);

    uv_close_cb close_cb;
    uv_close_cb *close_cb_p =
        luaL_checkudata(L, 2, "uv_close_cb");
    close_cb = *close_cb_p;

    uv_close(handle, close_cb);
    return 0;
}
int wrap_uv_default_loop(lua_State *L) {
    uv_loop_t * res = (uv_loop_t *)
        uv_default_loop();
    uv_loop_t * *res_ud =
        lua_newuserdata(L, sizeof(uv_loop_t *));
    if (res_ud != NULL) {
        *res_ud = res;
        printf("return wrap_uv_default_loop %p\n", *res_ud);

        luaL_newmetatable(L, "uv_loop_t_ptr");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int wrap_uv_err_name(lua_State *L) {
    uv_err_t err;
    uv_err_t *err_p =
        luaL_checkudata(L, 1, "uv_err_t");
    err = *err_p;

    char * res = (char *)
        uv_err_name(err);
    lua_pushstring(L, res);
    return 1;
}
int wrap_uv_exepath(lua_State *L) {
    char * buffer;
    buffer = (char *) luaL_checkstring(L, 1);

    size_t * size;
    size_t * *size_p =
        luaL_checkudata(L, 2, "size_t_ptr");
    size = *size_p;
    printf("  wrap_uv_exepath.size: %p\n", size);

    int res = (int)
        uv_exepath(buffer, size);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_chmod(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_chmod.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_chmod.req: %p\n", req);

    char * path;
    path = (char *) luaL_checkstring(L, 3);

    int mode;
    mode = (int) luaL_checkint(L, 4);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 5, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_chmod(loop, req, path, mode, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_chown(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_chown.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_chown.req: %p\n", req);

    char * path;
    path = (char *) luaL_checkstring(L, 3);

    int uid;
    uid = (int) luaL_checkint(L, 4);

    int gid;
    gid = (int) luaL_checkint(L, 5);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 6, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_chown(loop, req, path, uid, gid, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_close(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_close.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_close.req: %p\n", req);

    uv_file file;
    uv_file *file_p =
        luaL_checkudata(L, 3, "uv_file");
    file = *file_p;

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 4, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_close(loop, req, file, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_fchmod(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_fchmod.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_fchmod.req: %p\n", req);

    uv_file file;
    uv_file *file_p =
        luaL_checkudata(L, 3, "uv_file");
    file = *file_p;

    int mode;
    mode = (int) luaL_checkint(L, 4);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 5, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_fchmod(loop, req, file, mode, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_fchown(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_fchown.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_fchown.req: %p\n", req);

    uv_file file;
    uv_file *file_p =
        luaL_checkudata(L, 3, "uv_file");
    file = *file_p;

    int uid;
    uid = (int) luaL_checkint(L, 4);

    int gid;
    gid = (int) luaL_checkint(L, 5);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 6, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_fchown(loop, req, file, uid, gid, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_fdatasync(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_fdatasync.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_fdatasync.req: %p\n", req);

    uv_file file;
    uv_file *file_p =
        luaL_checkudata(L, 3, "uv_file");
    file = *file_p;

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 4, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_fdatasync(loop, req, file, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_fstat(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_fstat.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_fstat.req: %p\n", req);

    uv_file file;
    uv_file *file_p =
        luaL_checkudata(L, 3, "uv_file");
    file = *file_p;

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 4, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_fstat(loop, req, file, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_fsync(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_fsync.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_fsync.req: %p\n", req);

    uv_file file;
    uv_file *file_p =
        luaL_checkudata(L, 3, "uv_file");
    file = *file_p;

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 4, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_fsync(loop, req, file, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_ftruncate(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_ftruncate.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_ftruncate.req: %p\n", req);

    uv_file file;
    uv_file *file_p =
        luaL_checkudata(L, 3, "uv_file");
    file = *file_p;

    off_t offset;
    off_t *offset_p =
        luaL_checkudata(L, 4, "off_t");
    offset = *offset_p;

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 5, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_ftruncate(loop, req, file, offset, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_futime(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_futime.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_futime.req: %p\n", req);

    uv_file file;
    uv_file *file_p =
        luaL_checkudata(L, 3, "uv_file");
    file = *file_p;

    double atime;
    atime = (double) luaL_checknumber(L, 4);

    double mtime;
    mtime = (double) luaL_checknumber(L, 5);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 6, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_futime(loop, req, file, atime, mtime, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_link(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_link.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_link.req: %p\n", req);

    char * path;
    path = (char *) luaL_checkstring(L, 3);

    char * new_path;
    new_path = (char *) luaL_checkstring(L, 4);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 5, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_link(loop, req, path, new_path, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_lstat(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_lstat.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_lstat.req: %p\n", req);

    char * path;
    path = (char *) luaL_checkstring(L, 3);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 4, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_lstat(loop, req, path, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_mkdir(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_mkdir.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_mkdir.req: %p\n", req);

    char * path;
    path = (char *) luaL_checkstring(L, 3);

    int mode;
    mode = (int) luaL_checkint(L, 4);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 5, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_mkdir(loop, req, path, mode, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_open(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_open.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_open.req: %p\n", req);

    char * path;
    path = (char *) luaL_checkstring(L, 3);

    int flags;
    flags = (int) luaL_checkint(L, 4);

    int mode;
    mode = (int) luaL_checkint(L, 5);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 6, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_open(loop, req, path, flags, mode, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_read(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_read.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_read.req: %p\n", req);

    uv_file file;
    uv_file *file_p =
        luaL_checkudata(L, 3, "uv_file");
    file = *file_p;

    void * buf;
    void * *buf_p =
        luaL_checkudata(L, 4, "void_ptr");
    buf = *buf_p;
    printf("  wrap_uv_fs_read.buf: %p\n", buf);

    size_t length;
    length = (size_t) luaL_checklong(L, 5);

    off_t offset;
    off_t *offset_p =
        luaL_checkudata(L, 6, "off_t");
    offset = *offset_p;

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 7, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_read(loop, req, file, buf, length, offset, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_readdir(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_readdir.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_readdir.req: %p\n", req);

    char * path;
    path = (char *) luaL_checkstring(L, 3);

    int flags;
    flags = (int) luaL_checkint(L, 4);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 5, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_readdir(loop, req, path, flags, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_readlink(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_readlink.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_readlink.req: %p\n", req);

    char * path;
    path = (char *) luaL_checkstring(L, 3);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 4, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_readlink(loop, req, path, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_rename(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_rename.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_rename.req: %p\n", req);

    char * path;
    path = (char *) luaL_checkstring(L, 3);

    char * new_path;
    new_path = (char *) luaL_checkstring(L, 4);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 5, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_rename(loop, req, path, new_path, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_req_cleanup(lua_State *L) {
    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 1, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_req_cleanup.req: %p\n", req);

    uv_fs_req_cleanup(req);
    return 0;
}
int wrap_uv_fs_rmdir(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_rmdir.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_rmdir.req: %p\n", req);

    char * path;
    path = (char *) luaL_checkstring(L, 3);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 4, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_rmdir(loop, req, path, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_sendfile(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_sendfile.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_sendfile.req: %p\n", req);

    uv_file out_fd;
    uv_file *out_fd_p =
        luaL_checkudata(L, 3, "uv_file");
    out_fd = *out_fd_p;

    uv_file in_fd;
    uv_file *in_fd_p =
        luaL_checkudata(L, 4, "uv_file");
    in_fd = *in_fd_p;

    off_t in_offset;
    off_t *in_offset_p =
        luaL_checkudata(L, 5, "off_t");
    in_offset = *in_offset_p;

    size_t length;
    length = (size_t) luaL_checklong(L, 6);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 7, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_sendfile(loop, req, out_fd, in_fd, in_offset, length, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_stat(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_stat.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_stat.req: %p\n", req);

    char * path;
    path = (char *) luaL_checkstring(L, 3);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 4, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_stat(loop, req, path, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_symlink(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_symlink.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_symlink.req: %p\n", req);

    char * path;
    path = (char *) luaL_checkstring(L, 3);

    char * new_path;
    new_path = (char *) luaL_checkstring(L, 4);

    int flags;
    flags = (int) luaL_checkint(L, 5);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 6, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_symlink(loop, req, path, new_path, flags, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_unlink(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_unlink.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_unlink.req: %p\n", req);

    char * path;
    path = (char *) luaL_checkstring(L, 3);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 4, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_unlink(loop, req, path, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_utime(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_utime.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_utime.req: %p\n", req);

    char * path;
    path = (char *) luaL_checkstring(L, 3);

    double atime;
    atime = (double) luaL_checknumber(L, 4);

    double mtime;
    mtime = (double) luaL_checknumber(L, 5);

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 6, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_utime(loop, req, path, atime, mtime, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_fs_write(lua_State *L) {
    uv_loop_t * loop;
    uv_loop_t * *loop_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    loop = *loop_p;
    printf("  wrap_uv_fs_write.loop: %p\n", loop);

    uv_fs_t * req;
    uv_fs_t * *req_p =
        luaL_checkudata(L, 2, "uv_fs_t_ptr");
    req = *req_p;
    printf("  wrap_uv_fs_write.req: %p\n", req);

    uv_file file;
    uv_file *file_p =
        luaL_checkudata(L, 3, "uv_file");
    file = *file_p;

    void * buf;
    void * *buf_p =
        luaL_checkudata(L, 4, "void_ptr");
    buf = *buf_p;
    printf("  wrap_uv_fs_write.buf: %p\n", buf);

    size_t length;
    length = (size_t) luaL_checklong(L, 5);

    off_t offset;
    off_t *offset_p =
        luaL_checkudata(L, 6, "off_t");
    offset = *offset_p;

    uv_fs_cb cb;
    uv_fs_cb *cb_p =
        luaL_checkudata(L, 7, "uv_fs_cb");
    cb = *cb_p;

    int res = (int)
        uv_fs_write(loop, req, file, buf, length, offset, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_getaddrinfo(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_getaddrinfo.arg_0: %p\n", arg_0);

    uv_getaddrinfo_t * handle;
    uv_getaddrinfo_t * *handle_p =
        luaL_checkudata(L, 2, "uv_getaddrinfo_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_getaddrinfo.handle: %p\n", handle);

    uv_getaddrinfo_cb getaddrinfo_cb;
    uv_getaddrinfo_cb *getaddrinfo_cb_p =
        luaL_checkudata(L, 3, "uv_getaddrinfo_cb");
    getaddrinfo_cb = *getaddrinfo_cb_p;

    char * node;
    node = (char *) luaL_checkstring(L, 4);

    char * service;
    service = (char *) luaL_checkstring(L, 5);

    struct addrinfo * hints;
    struct addrinfo * *hints_p =
        luaL_checkudata(L, 6, "addrinfo_ptr");
    hints = *hints_p;
    printf("  wrap_uv_getaddrinfo.hints: %p\n", hints);

    int res = (int)
        uv_getaddrinfo(arg_0, handle, getaddrinfo_cb, node, service, hints);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_hrtime(lua_State *L) {
    uint64_t res = (uint64_t)
        uv_hrtime();
    uint64_t *res_ud =
        lua_newuserdata(L, sizeof(uint64_t));
    if (res_ud != NULL) {
        *res_ud = res;

        luaL_newmetatable(L, "uint64_t");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int wrap_uv_idle_init(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_idle_init.arg_0: %p\n", arg_0);

    uv_idle_t * idle;
    uv_idle_t * *idle_p =
        luaL_checkudata(L, 2, "uv_idle_t_ptr");
    idle = *idle_p;
    printf("  wrap_uv_idle_init.idle: %p\n", idle);

    int res = (int)
        uv_idle_init(arg_0, idle);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_idle_start(lua_State *L) {
    uv_idle_t * idle;
    uv_idle_t * *idle_p =
        luaL_checkudata(L, 1, "uv_idle_t_ptr");
    idle = *idle_p;
    printf("  wrap_uv_idle_start.idle: %p\n", idle);

    uv_idle_cb cb;
    uv_idle_cb *cb_p =
        luaL_checkudata(L, 2, "uv_idle_cb");
    cb = *cb_p;

    int res = (int)
        uv_idle_start(idle, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_idle_stop(lua_State *L) {
    uv_idle_t * idle;
    uv_idle_t * *idle_p =
        luaL_checkudata(L, 1, "uv_idle_t_ptr");
    idle = *idle_p;
    printf("  wrap_uv_idle_stop.idle: %p\n", idle);

    int res = (int)
        uv_idle_stop(idle);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_ip4_addr(lua_State *L) {
    char * ip;
    ip = (char *) luaL_checkstring(L, 1);

    int port;
    port = (int) luaL_checkint(L, 2);

    struct sockaddr_in res = (struct sockaddr_in)
        uv_ip4_addr(ip, port);
    struct sockaddr_in *res_ud =
        lua_newuserdata(L, sizeof(struct sockaddr_in));
    if (res_ud != NULL) {
        *res_ud = res;

        luaL_newmetatable(L, "sockaddr_in");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int wrap_uv_ip4_name(lua_State *L) {
    struct sockaddr_in * src;
    struct sockaddr_in * *src_p =
        luaL_checkudata(L, 1, "sockaddr_in_ptr");
    src = *src_p;
    printf("  wrap_uv_ip4_name.src: %p\n", src);

    char * dst;
    dst = (char *) luaL_checkstring(L, 2);

    size_t size;
    size = (size_t) luaL_checklong(L, 3);

    int res = (int)
        uv_ip4_name(src, dst, size);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_ip6_addr(lua_State *L) {
    char * ip;
    ip = (char *) luaL_checkstring(L, 1);

    int port;
    port = (int) luaL_checkint(L, 2);

    struct sockaddr_in6 res = (struct sockaddr_in6)
        uv_ip6_addr(ip, port);
    struct sockaddr_in6 *res_ud =
        lua_newuserdata(L, sizeof(struct sockaddr_in6));
    if (res_ud != NULL) {
        *res_ud = res;

        luaL_newmetatable(L, "sockaddr_in6");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int wrap_uv_ip6_name(lua_State *L) {
    struct sockaddr_in6 * src;
    struct sockaddr_in6 * *src_p =
        luaL_checkudata(L, 1, "sockaddr_in6_ptr");
    src = *src_p;
    printf("  wrap_uv_ip6_name.src: %p\n", src);

    char * dst;
    dst = (char *) luaL_checkstring(L, 2);

    size_t size;
    size = (size_t) luaL_checklong(L, 3);

    int res = (int)
        uv_ip6_name(src, dst, size);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_is_active(lua_State *L) {
    uv_handle_t * handle;
    uv_handle_t * *handle_p =
        luaL_checkudata(L, 1, "uv_handle_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_is_active.handle: %p\n", handle);

    int res = (int)
        uv_is_active(handle);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_is_tty(lua_State *L) {
    uv_file file;
    uv_file *file_p =
        luaL_checkudata(L, 1, "uv_file");
    file = *file_p;

    int res = (int)
        uv_is_tty(file);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_last_error(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_last_error.arg_0: %p\n", arg_0);

    uv_err_t res = (uv_err_t)
        uv_last_error(arg_0);
    uv_err_t *res_ud =
        lua_newuserdata(L, sizeof(uv_err_t));
    if (res_ud != NULL) {
        *res_ud = res;

        luaL_newmetatable(L, "uv_err_t");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int wrap_uv_loop_delete(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_loop_delete.arg_0: %p\n", arg_0);

    uv_loop_delete(arg_0);
    return 0;
}
int wrap_uv_loop_new(lua_State *L) {
    uv_loop_t * res = (uv_loop_t *)
        uv_loop_new();
    uv_loop_t * *res_ud =
        lua_newuserdata(L, sizeof(uv_loop_t *));
    if (res_ud != NULL) {
        *res_ud = res;
        printf("return wrap_uv_loop_new %p\n", *res_ud);

        luaL_newmetatable(L, "uv_loop_t_ptr");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int wrap_uv_now(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_now.arg_0: %p\n", arg_0);

    int64_t res = (int64_t)
        uv_now(arg_0);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_pipe_bind(lua_State *L) {
    uv_pipe_t * handle;
    uv_pipe_t * *handle_p =
        luaL_checkudata(L, 1, "uv_pipe_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_pipe_bind.handle: %p\n", handle);

    char * name;
    name = (char *) luaL_checkstring(L, 2);

    int res = (int)
        uv_pipe_bind(handle, name);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_pipe_connect(lua_State *L) {
    uv_connect_t * req;
    uv_connect_t * *req_p =
        luaL_checkudata(L, 1, "uv_connect_t_ptr");
    req = *req_p;
    printf("  wrap_uv_pipe_connect.req: %p\n", req);

    uv_pipe_t * handle;
    uv_pipe_t * *handle_p =
        luaL_checkudata(L, 2, "uv_pipe_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_pipe_connect.handle: %p\n", handle);

    char * name;
    name = (char *) luaL_checkstring(L, 3);

    uv_connect_cb cb;
    uv_connect_cb *cb_p =
        luaL_checkudata(L, 4, "uv_connect_cb");
    cb = *cb_p;

    int res = (int)
        uv_pipe_connect(req, handle, name, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_pipe_init(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_pipe_init.arg_0: %p\n", arg_0);

    uv_pipe_t * handle;
    uv_pipe_t * *handle_p =
        luaL_checkudata(L, 2, "uv_pipe_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_pipe_init.handle: %p\n", handle);

    int res = (int)
        uv_pipe_init(arg_0, handle);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_pipe_open(lua_State *L) {
    uv_pipe_t * arg_0;
    uv_pipe_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_pipe_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_pipe_open.arg_0: %p\n", arg_0);

    uv_file file;
    uv_file *file_p =
        luaL_checkudata(L, 2, "uv_file");
    file = *file_p;

    uv_pipe_open(arg_0, file);
    return 0;
}
int wrap_uv_prepare_init(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_prepare_init.arg_0: %p\n", arg_0);

    uv_prepare_t * prepare;
    uv_prepare_t * *prepare_p =
        luaL_checkudata(L, 2, "uv_prepare_t_ptr");
    prepare = *prepare_p;
    printf("  wrap_uv_prepare_init.prepare: %p\n", prepare);

    int res = (int)
        uv_prepare_init(arg_0, prepare);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_prepare_start(lua_State *L) {
    uv_prepare_t * prepare;
    uv_prepare_t * *prepare_p =
        luaL_checkudata(L, 1, "uv_prepare_t_ptr");
    prepare = *prepare_p;
    printf("  wrap_uv_prepare_start.prepare: %p\n", prepare);

    uv_prepare_cb cb;
    uv_prepare_cb *cb_p =
        luaL_checkudata(L, 2, "uv_prepare_cb");
    cb = *cb_p;

    int res = (int)
        uv_prepare_start(prepare, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_prepare_stop(lua_State *L) {
    uv_prepare_t * prepare;
    uv_prepare_t * *prepare_p =
        luaL_checkudata(L, 1, "uv_prepare_t_ptr");
    prepare = *prepare_p;
    printf("  wrap_uv_prepare_stop.prepare: %p\n", prepare);

    int res = (int)
        uv_prepare_stop(prepare);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_process_kill(lua_State *L) {
    uv_process_t * arg_0;
    uv_process_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_process_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_process_kill.arg_0: %p\n", arg_0);

    int signum;
    signum = (int) luaL_checkint(L, 2);

    int res = (int)
        uv_process_kill(arg_0, signum);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_read_stop(lua_State *L) {
    uv_stream_t * arg_0;
    uv_stream_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_stream_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_read_stop.arg_0: %p\n", arg_0);

    int res = (int)
        uv_read_stop(arg_0);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_ref(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_ref.arg_0: %p\n", arg_0);

    uv_ref(arg_0);
    return 0;
}
int wrap_uv_run(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_run.arg_0: %p\n", arg_0);

    int res = (int)
        uv_run(arg_0);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_shutdown(lua_State *L) {
    uv_shutdown_t * req;
    uv_shutdown_t * *req_p =
        luaL_checkudata(L, 1, "uv_shutdown_t_ptr");
    req = *req_p;
    printf("  wrap_uv_shutdown.req: %p\n", req);

    uv_stream_t * handle;
    uv_stream_t * *handle_p =
        luaL_checkudata(L, 2, "uv_stream_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_shutdown.handle: %p\n", handle);

    uv_shutdown_cb cb;
    uv_shutdown_cb *cb_p =
        luaL_checkudata(L, 3, "uv_shutdown_cb");
    cb = *cb_p;

    int res = (int)
        uv_shutdown(req, handle, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_spawn(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_spawn.arg_0: %p\n", arg_0);

    uv_process_t * arg_1;
    uv_process_t * *arg_1_p =
        luaL_checkudata(L, 2, "uv_process_t_ptr");
    arg_1 = *arg_1_p;
    printf("  wrap_uv_spawn.arg_1: %p\n", arg_1);

    uv_process_options_t options;
    uv_process_options_t *options_p =
        luaL_checkudata(L, 3, "uv_process_options_t");
    options = *options_p;

    int res = (int)
        uv_spawn(arg_0, arg_1, options);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_std_handle(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_std_handle.arg_0: %p\n", arg_0);

    uv_std_type type;
    type = (uv_std_type) luaL_checkint(L, 2);

    uv_stream_t * res = (uv_stream_t *)
        uv_std_handle(arg_0, type);
    uv_stream_t * *res_ud =
        lua_newuserdata(L, sizeof(uv_stream_t *));
    if (res_ud != NULL) {
        *res_ud = res;
        printf("return wrap_uv_std_handle %p\n", *res_ud);

        luaL_newmetatable(L, "uv_stream_t_ptr");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int wrap_uv_strerror(lua_State *L) {
    uv_err_t err;
    uv_err_t *err_p =
        luaL_checkudata(L, 1, "uv_err_t");
    err = *err_p;

    char * res = (char *)
        uv_strerror(err);
    lua_pushstring(L, res);
    return 1;
}
int wrap_uv_tcp_bind(lua_State *L) {
    uv_tcp_t * handle;
    uv_tcp_t * *handle_p =
        luaL_checkudata(L, 1, "uv_tcp_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_tcp_bind.handle: %p\n", handle);

    struct sockaddr_in arg_1;
    struct sockaddr_in *arg_1_p =
        luaL_checkudata(L, 2, "sockaddr_in");
    arg_1 = *arg_1_p;

    int res = (int)
        uv_tcp_bind(handle, arg_1);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_tcp_bind6(lua_State *L) {
    uv_tcp_t * handle;
    uv_tcp_t * *handle_p =
        luaL_checkudata(L, 1, "uv_tcp_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_tcp_bind6.handle: %p\n", handle);

    struct sockaddr_in6 arg_1;
    struct sockaddr_in6 *arg_1_p =
        luaL_checkudata(L, 2, "sockaddr_in6");
    arg_1 = *arg_1_p;

    int res = (int)
        uv_tcp_bind6(handle, arg_1);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_tcp_connect(lua_State *L) {
    uv_connect_t * req;
    uv_connect_t * *req_p =
        luaL_checkudata(L, 1, "uv_connect_t_ptr");
    req = *req_p;
    printf("  wrap_uv_tcp_connect.req: %p\n", req);

    uv_tcp_t * handle;
    uv_tcp_t * *handle_p =
        luaL_checkudata(L, 2, "uv_tcp_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_tcp_connect.handle: %p\n", handle);

    struct sockaddr_in address;
    struct sockaddr_in *address_p =
        luaL_checkudata(L, 3, "sockaddr_in");
    address = *address_p;

    uv_connect_cb cb;
    uv_connect_cb *cb_p =
        luaL_checkudata(L, 4, "uv_connect_cb");
    cb = *cb_p;

    int res = (int)
        uv_tcp_connect(req, handle, address, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_tcp_connect6(lua_State *L) {
    uv_connect_t * req;
    uv_connect_t * *req_p =
        luaL_checkudata(L, 1, "uv_connect_t_ptr");
    req = *req_p;
    printf("  wrap_uv_tcp_connect6.req: %p\n", req);

    uv_tcp_t * handle;
    uv_tcp_t * *handle_p =
        luaL_checkudata(L, 2, "uv_tcp_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_tcp_connect6.handle: %p\n", handle);

    struct sockaddr_in6 address;
    struct sockaddr_in6 *address_p =
        luaL_checkudata(L, 3, "sockaddr_in6");
    address = *address_p;

    uv_connect_cb cb;
    uv_connect_cb *cb_p =
        luaL_checkudata(L, 4, "uv_connect_cb");
    cb = *cb_p;

    int res = (int)
        uv_tcp_connect6(req, handle, address, cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_tcp_getpeername(lua_State *L) {
    uv_tcp_t * handle;
    uv_tcp_t * *handle_p =
        luaL_checkudata(L, 1, "uv_tcp_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_tcp_getpeername.handle: %p\n", handle);

    struct sockaddr * name;
    struct sockaddr * *name_p =
        luaL_checkudata(L, 2, "sockaddr_ptr");
    name = *name_p;
    printf("  wrap_uv_tcp_getpeername.name: %p\n", name);

    int * namelen;
    int * *namelen_p =
        luaL_checkudata(L, 3, "int_ptr");
    namelen = *namelen_p;
    printf("  wrap_uv_tcp_getpeername.namelen: %p\n", namelen);

    int res = (int)
        uv_tcp_getpeername(handle, name, namelen);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_tcp_getsockname(lua_State *L) {
    uv_tcp_t * handle;
    uv_tcp_t * *handle_p =
        luaL_checkudata(L, 1, "uv_tcp_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_tcp_getsockname.handle: %p\n", handle);

    struct sockaddr * name;
    struct sockaddr * *name_p =
        luaL_checkudata(L, 2, "sockaddr_ptr");
    name = *name_p;
    printf("  wrap_uv_tcp_getsockname.name: %p\n", name);

    int * namelen;
    int * *namelen_p =
        luaL_checkudata(L, 3, "int_ptr");
    namelen = *namelen_p;
    printf("  wrap_uv_tcp_getsockname.namelen: %p\n", namelen);

    int res = (int)
        uv_tcp_getsockname(handle, name, namelen);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_tcp_init(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_tcp_init.arg_0: %p\n", arg_0);

    uv_tcp_t * handle;
    uv_tcp_t * *handle_p =
        luaL_checkudata(L, 2, "uv_tcp_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_tcp_init.handle: %p\n", handle);

    int res = (int)
        uv_tcp_init(arg_0, handle);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_timer_again(lua_State *L) {
    uv_timer_t * timer;
    uv_timer_t * *timer_p =
        luaL_checkudata(L, 1, "uv_timer_t_ptr");
    timer = *timer_p;
    printf("  wrap_uv_timer_again.timer: %p\n", timer);

    int res = (int)
        uv_timer_again(timer);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_timer_get_repeat(lua_State *L) {
    uv_timer_t * timer;
    uv_timer_t * *timer_p =
        luaL_checkudata(L, 1, "uv_timer_t_ptr");
    timer = *timer_p;
    printf("  wrap_uv_timer_get_repeat.timer: %p\n", timer);

    int64_t res = (int64_t)
        uv_timer_get_repeat(timer);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_timer_init(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_timer_init.arg_0: %p\n", arg_0);

    uv_timer_t * timer;
    uv_timer_t * *timer_p =
        luaL_checkudata(L, 2, "uv_timer_t_ptr");
    timer = *timer_p;
    printf("  wrap_uv_timer_init.timer: %p\n", timer);

    int res = (int)
        uv_timer_init(arg_0, timer);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_timer_set_repeat(lua_State *L) {
    uv_timer_t * timer;
    uv_timer_t * *timer_p =
        luaL_checkudata(L, 1, "uv_timer_t_ptr");
    timer = *timer_p;
    printf("  wrap_uv_timer_set_repeat.timer: %p\n", timer);

    int64_t repeat;
    repeat = (int64_t) luaL_checklong(L, 2);

    uv_timer_set_repeat(timer, repeat);
    return 0;
}
int wrap_uv_timer_start(lua_State *L) {
    uv_timer_t * timer;
    uv_timer_t * *timer_p =
        luaL_checkudata(L, 1, "uv_timer_t_ptr");
    timer = *timer_p;
    printf("  wrap_uv_timer_start.timer: %p\n", timer);

    uv_timer_cb cb;
    uv_timer_cb *cb_p =
        luaL_checkudata(L, 2, "uv_timer_cb");
    cb = *cb_p;

    int64_t timeout;
    timeout = (int64_t) luaL_checklong(L, 3);

    int64_t repeat;
    repeat = (int64_t) luaL_checklong(L, 4);

    int res = (int)
        uv_timer_start(timer, cb, timeout, repeat);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_timer_stop(lua_State *L) {
    uv_timer_t * timer;
    uv_timer_t * *timer_p =
        luaL_checkudata(L, 1, "uv_timer_t_ptr");
    timer = *timer_p;
    printf("  wrap_uv_timer_stop.timer: %p\n", timer);

    int res = (int)
        uv_timer_stop(timer);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_tty_init(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_tty_init.arg_0: %p\n", arg_0);

    uv_tty_t * arg_1;
    uv_tty_t * *arg_1_p =
        luaL_checkudata(L, 2, "uv_tty_t_ptr");
    arg_1 = *arg_1_p;
    printf("  wrap_uv_tty_init.arg_1: %p\n", arg_1);

    uv_file fd;
    uv_file *fd_p =
        luaL_checkudata(L, 3, "uv_file");
    fd = *fd_p;

    int res = (int)
        uv_tty_init(arg_0, arg_1, fd);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_tty_set_mode(lua_State *L) {
    uv_tty_t * arg_0;
    uv_tty_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_tty_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_tty_set_mode.arg_0: %p\n", arg_0);

    int mode;
    mode = (int) luaL_checkint(L, 2);

    int res = (int)
        uv_tty_set_mode(arg_0, mode);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_udp_bind(lua_State *L) {
    uv_udp_t * handle;
    uv_udp_t * *handle_p =
        luaL_checkudata(L, 1, "uv_udp_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_udp_bind.handle: %p\n", handle);

    struct sockaddr_in addr;
    struct sockaddr_in *addr_p =
        luaL_checkudata(L, 2, "sockaddr_in");
    addr = *addr_p;

    unsigned flags;
    unsigned *flags_p =
        luaL_checkudata(L, 3, "unsigned");
    flags = *flags_p;

    int res = (int)
        uv_udp_bind(handle, addr, flags);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_udp_bind6(lua_State *L) {
    uv_udp_t * handle;
    uv_udp_t * *handle_p =
        luaL_checkudata(L, 1, "uv_udp_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_udp_bind6.handle: %p\n", handle);

    struct sockaddr_in6 addr;
    struct sockaddr_in6 *addr_p =
        luaL_checkudata(L, 2, "sockaddr_in6");
    addr = *addr_p;

    unsigned flags;
    unsigned *flags_p =
        luaL_checkudata(L, 3, "unsigned");
    flags = *flags_p;

    int res = (int)
        uv_udp_bind6(handle, addr, flags);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_udp_getsockname(lua_State *L) {
    uv_udp_t * handle;
    uv_udp_t * *handle_p =
        luaL_checkudata(L, 1, "uv_udp_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_udp_getsockname.handle: %p\n", handle);

    struct sockaddr * name;
    struct sockaddr * *name_p =
        luaL_checkudata(L, 2, "sockaddr_ptr");
    name = *name_p;
    printf("  wrap_uv_udp_getsockname.name: %p\n", name);

    int * namelen;
    int * *namelen_p =
        luaL_checkudata(L, 3, "int_ptr");
    namelen = *namelen_p;
    printf("  wrap_uv_udp_getsockname.namelen: %p\n", namelen);

    int res = (int)
        uv_udp_getsockname(handle, name, namelen);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_udp_init(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_udp_init.arg_0: %p\n", arg_0);

    uv_udp_t * handle;
    uv_udp_t * *handle_p =
        luaL_checkudata(L, 2, "uv_udp_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_udp_init.handle: %p\n", handle);

    int res = (int)
        uv_udp_init(arg_0, handle);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_udp_recv_start(lua_State *L) {
    uv_udp_t * handle;
    uv_udp_t * *handle_p =
        luaL_checkudata(L, 1, "uv_udp_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_udp_recv_start.handle: %p\n", handle);

    uv_alloc_cb alloc_cb;
    uv_alloc_cb *alloc_cb_p =
        luaL_checkudata(L, 2, "uv_alloc_cb");
    alloc_cb = *alloc_cb_p;

    uv_udp_recv_cb recv_cb;
    uv_udp_recv_cb *recv_cb_p =
        luaL_checkudata(L, 3, "uv_udp_recv_cb");
    recv_cb = *recv_cb_p;

    int res = (int)
        uv_udp_recv_start(handle, alloc_cb, recv_cb);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_udp_recv_stop(lua_State *L) {
    uv_udp_t * handle;
    uv_udp_t * *handle_p =
        luaL_checkudata(L, 1, "uv_udp_t_ptr");
    handle = *handle_p;
    printf("  wrap_uv_udp_recv_stop.handle: %p\n", handle);

    int res = (int)
        uv_udp_recv_stop(handle);
    lua_pushinteger(L, res);
    return 1;
}
int wrap_uv_unref(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_unref.arg_0: %p\n", arg_0);

    uv_unref(arg_0);
    return 0;
}
int wrap_uv_update_time(lua_State *L) {
    uv_loop_t * arg_0;
    uv_loop_t * *arg_0_p =
        luaL_checkudata(L, 1, "uv_loop_t_ptr");
    arg_0 = *arg_0_p;
    printf("  wrap_uv_update_time.arg_0: %p\n", arg_0);

    uv_update_time(arg_0);
    return 0;
}
int alloc_sockaddr_in_ptr(lua_State *L) {
    struct sockaddr_in * *pp =
        lua_newuserdata(L, sizeof(struct sockaddr_in *) + sizeof(struct sockaddr_in));
    if (pp != NULL) {
        *pp = (struct sockaddr_in *) &pp[1];
        printf("return alloc_sockaddr_in_ptr %p\n", *pp);
        luaL_newmetatable(L, "sockaddr_in_ptr");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int deref_sockaddr_in_ptr(lua_State *L) {
    struct sockaddr_in *p;
    struct sockaddr_in * *pp =
        luaL_checkudata(L, 1, "sockaddr_in_ptr");
    p = *pp;

    struct sockaddr_in *res =
        lua_newuserdata(L, sizeof(*res));
    if (res != NULL) {
        *res = *p;
        luaL_newmetatable(L, "sockaddr_in");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int alloc_sockaddr_in6_ptr(lua_State *L) {
    struct sockaddr_in6 * *pp =
        lua_newuserdata(L, sizeof(struct sockaddr_in6 *) + sizeof(struct sockaddr_in6));
    if (pp != NULL) {
        *pp = (struct sockaddr_in6 *) &pp[1];
        printf("return alloc_sockaddr_in6_ptr %p\n", *pp);
        luaL_newmetatable(L, "sockaddr_in6_ptr");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int deref_sockaddr_in6_ptr(lua_State *L) {
    struct sockaddr_in6 *p;
    struct sockaddr_in6 * *pp =
        luaL_checkudata(L, 1, "sockaddr_in6_ptr");
    p = *pp;

    struct sockaddr_in6 *res =
        lua_newuserdata(L, sizeof(*res));
    if (res != NULL) {
        *res = *p;
        luaL_newmetatable(L, "sockaddr_in6");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int alloc_uv_pipe_t_ptr(lua_State *L) {
    uv_pipe_t * *pp =
        lua_newuserdata(L, sizeof(uv_pipe_t *) + sizeof(uv_pipe_t));
    if (pp != NULL) {
        *pp = (uv_pipe_t *) &pp[1];
        printf("return alloc_uv_pipe_t_ptr %p\n", *pp);
        luaL_newmetatable(L, "uv_pipe_t_ptr");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int deref_uv_pipe_t_ptr(lua_State *L) {
    uv_pipe_t *p;
    uv_pipe_t * *pp =
        luaL_checkudata(L, 1, "uv_pipe_t_ptr");
    p = *pp;

    uv_pipe_t *res =
        lua_newuserdata(L, sizeof(*res));
    if (res != NULL) {
        *res = *p;
        luaL_newmetatable(L, "uv_pipe_t");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int cast_uv_pipe_t_ptr_to_uv_stream_t_ptr(lua_State *L) {
    uv_pipe_t *p;
    uv_pipe_t * *pp =
        luaL_checkudata(L, 1, "uv_pipe_t_ptr");
    p = *pp;

    uv_stream_t * *res =
        lua_newuserdata(L, sizeof(*res));
    if (res != NULL) {
        *res = (uv_stream_t *) p;
        printf("return cast_uv_pipe_t_ptr_to_uv_stream_t_ptr_ptr %p\n", *res);
        luaL_newmetatable(L, "uv_stream_t_ptr");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int alloc_uv_tcp_t_ptr(lua_State *L) {
    uv_tcp_t * *pp =
        lua_newuserdata(L, sizeof(uv_tcp_t *) + sizeof(uv_tcp_t));
    if (pp != NULL) {
        *pp = (uv_tcp_t *) &pp[1];
        printf("return alloc_uv_tcp_t_ptr %p\n", *pp);
        luaL_newmetatable(L, "uv_tcp_t_ptr");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int deref_uv_tcp_t_ptr(lua_State *L) {
    uv_tcp_t *p;
    uv_tcp_t * *pp =
        luaL_checkudata(L, 1, "uv_tcp_t_ptr");
    p = *pp;

    uv_tcp_t *res =
        lua_newuserdata(L, sizeof(*res));
    if (res != NULL) {
        *res = *p;
        luaL_newmetatable(L, "uv_tcp_t");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int cast_uv_tcp_t_ptr_to_uv_stream_t_ptr(lua_State *L) {
    uv_tcp_t *p;
    uv_tcp_t * *pp =
        luaL_checkudata(L, 1, "uv_tcp_t_ptr");
    p = *pp;

    uv_stream_t * *res =
        lua_newuserdata(L, sizeof(*res));
    if (res != NULL) {
        *res = (uv_stream_t *) p;
        printf("return cast_uv_tcp_t_ptr_to_uv_stream_t_ptr_ptr %p\n", *res);
        luaL_newmetatable(L, "uv_stream_t_ptr");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int alloc_uv_udp_t_ptr(lua_State *L) {
    uv_udp_t * *pp =
        lua_newuserdata(L, sizeof(uv_udp_t *) + sizeof(uv_udp_t));
    if (pp != NULL) {
        *pp = (uv_udp_t *) &pp[1];
        printf("return alloc_uv_udp_t_ptr %p\n", *pp);
        luaL_newmetatable(L, "uv_udp_t_ptr");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int deref_uv_udp_t_ptr(lua_State *L) {
    uv_udp_t *p;
    uv_udp_t * *pp =
        luaL_checkudata(L, 1, "uv_udp_t_ptr");
    p = *pp;

    uv_udp_t *res =
        lua_newuserdata(L, sizeof(*res));
    if (res != NULL) {
        *res = *p;
        luaL_newmetatable(L, "uv_udp_t");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int cast_uv_udp_t_ptr_to_uv_stream_t_ptr(lua_State *L) {
    uv_udp_t *p;
    uv_udp_t * *pp =
        luaL_checkudata(L, 1, "uv_udp_t_ptr");
    p = *pp;

    uv_stream_t * *res =
        lua_newuserdata(L, sizeof(*res));
    if (res != NULL) {
        *res = (uv_stream_t *) p;
        printf("return cast_uv_udp_t_ptr_to_uv_stream_t_ptr_ptr %p\n", *res);
        luaL_newmetatable(L, "uv_stream_t_ptr");
        lua_setmetatable(L, -2);
        return 1;
    }
    return 0;
}
int alloc_sockaddr_in6_ptr(lua_State *L);
int alloc_sockaddr_in_ptr(lua_State *L);
int alloc_uv_pipe_t_ptr(lua_State *L);
int alloc_uv_tcp_t_ptr(lua_State *L);
int alloc_uv_udp_t_ptr(lua_State *L);
int cast_uv_pipe_t_ptr_to_uv_stream_t_ptr(lua_State *L);
int cast_uv_tcp_t_ptr_to_uv_stream_t_ptr(lua_State *L);
int cast_uv_udp_t_ptr_to_uv_stream_t_ptr(lua_State *L);
int deref_sockaddr_in6_ptr(lua_State *L);
int deref_sockaddr_in_ptr(lua_State *L);
int deref_uv_pipe_t_ptr(lua_State *L);
int deref_uv_tcp_t_ptr(lua_State *L);
int deref_uv_udp_t_ptr(lua_State *L);
int wrap_uv_accept(lua_State *L);
int wrap_uv_ares_destroy(lua_State *L);
int wrap_uv_ares_init_options(lua_State *L);
int wrap_uv_async_init(lua_State *L);
int wrap_uv_async_send(lua_State *L);
int wrap_uv_buf_init(lua_State *L);
int wrap_uv_check_init(lua_State *L);
int wrap_uv_check_start(lua_State *L);
int wrap_uv_check_stop(lua_State *L);
int wrap_uv_cleanup(lua_State *L);
int wrap_uv_close(lua_State *L);
int wrap_uv_default_loop(lua_State *L);
int wrap_uv_err_name(lua_State *L);
int wrap_uv_exepath(lua_State *L);
int wrap_uv_fs_chmod(lua_State *L);
int wrap_uv_fs_chown(lua_State *L);
int wrap_uv_fs_close(lua_State *L);
int wrap_uv_fs_fchmod(lua_State *L);
int wrap_uv_fs_fchown(lua_State *L);
int wrap_uv_fs_fdatasync(lua_State *L);
int wrap_uv_fs_fstat(lua_State *L);
int wrap_uv_fs_fsync(lua_State *L);
int wrap_uv_fs_ftruncate(lua_State *L);
int wrap_uv_fs_futime(lua_State *L);
int wrap_uv_fs_link(lua_State *L);
int wrap_uv_fs_lstat(lua_State *L);
int wrap_uv_fs_mkdir(lua_State *L);
int wrap_uv_fs_open(lua_State *L);
int wrap_uv_fs_read(lua_State *L);
int wrap_uv_fs_readdir(lua_State *L);
int wrap_uv_fs_readlink(lua_State *L);
int wrap_uv_fs_rename(lua_State *L);
int wrap_uv_fs_req_cleanup(lua_State *L);
int wrap_uv_fs_rmdir(lua_State *L);
int wrap_uv_fs_sendfile(lua_State *L);
int wrap_uv_fs_stat(lua_State *L);
int wrap_uv_fs_symlink(lua_State *L);
int wrap_uv_fs_unlink(lua_State *L);
int wrap_uv_fs_utime(lua_State *L);
int wrap_uv_fs_write(lua_State *L);
int wrap_uv_getaddrinfo(lua_State *L);
int wrap_uv_hrtime(lua_State *L);
int wrap_uv_idle_init(lua_State *L);
int wrap_uv_idle_start(lua_State *L);
int wrap_uv_idle_stop(lua_State *L);
int wrap_uv_ip4_addr(lua_State *L);
int wrap_uv_ip4_name(lua_State *L);
int wrap_uv_ip6_addr(lua_State *L);
int wrap_uv_ip6_name(lua_State *L);
int wrap_uv_is_active(lua_State *L);
int wrap_uv_is_tty(lua_State *L);
int wrap_uv_last_error(lua_State *L);
int wrap_uv_listen(lua_State *L);
int wrap_uv_loop_delete(lua_State *L);
int wrap_uv_loop_new(lua_State *L);
int wrap_uv_now(lua_State *L);
int wrap_uv_pipe_bind(lua_State *L);
int wrap_uv_pipe_connect(lua_State *L);
int wrap_uv_pipe_init(lua_State *L);
int wrap_uv_pipe_open(lua_State *L);
int wrap_uv_prepare_init(lua_State *L);
int wrap_uv_prepare_start(lua_State *L);
int wrap_uv_prepare_stop(lua_State *L);
int wrap_uv_process_kill(lua_State *L);
int wrap_uv_queue_work(lua_State *L);
int wrap_uv_read_start(lua_State *L);
int wrap_uv_read_stop(lua_State *L);
int wrap_uv_ref(lua_State *L);
int wrap_uv_run(lua_State *L);
int wrap_uv_shutdown(lua_State *L);
int wrap_uv_spawn(lua_State *L);
int wrap_uv_std_handle(lua_State *L);
int wrap_uv_strerror(lua_State *L);
int wrap_uv_tcp_bind(lua_State *L);
int wrap_uv_tcp_bind6(lua_State *L);
int wrap_uv_tcp_connect(lua_State *L);
int wrap_uv_tcp_connect6(lua_State *L);
int wrap_uv_tcp_getpeername(lua_State *L);
int wrap_uv_tcp_getsockname(lua_State *L);
int wrap_uv_tcp_init(lua_State *L);
int wrap_uv_timer_again(lua_State *L);
int wrap_uv_timer_get_repeat(lua_State *L);
int wrap_uv_timer_init(lua_State *L);
int wrap_uv_timer_set_repeat(lua_State *L);
int wrap_uv_timer_start(lua_State *L);
int wrap_uv_timer_stop(lua_State *L);
int wrap_uv_tty_init(lua_State *L);
int wrap_uv_tty_set_mode(lua_State *L);
int wrap_uv_udp_bind(lua_State *L);
int wrap_uv_udp_bind6(lua_State *L);
int wrap_uv_udp_getsockname(lua_State *L);
int wrap_uv_udp_init(lua_State *L);
int wrap_uv_udp_recv_start(lua_State *L);
int wrap_uv_udp_recv_stop(lua_State *L);
int wrap_uv_unref(lua_State *L);
int wrap_uv_update_time(lua_State *L);
int wrap_uv_write(lua_State *L);
LUA_API int luaopen_uv_wrap(lua_State *L) {
    luaL_reg reg[] = {
        {"alloc_sockaddr_in6_ptr", alloc_sockaddr_in6_ptr},
        {"alloc_sockaddr_in_ptr", alloc_sockaddr_in_ptr},
        {"alloc_uv_pipe_t_ptr", alloc_uv_pipe_t_ptr},
        {"alloc_uv_tcp_t_ptr", alloc_uv_tcp_t_ptr},
        {"alloc_uv_udp_t_ptr", alloc_uv_udp_t_ptr},
        {"cast_uv_pipe_t_ptr_to_uv_stream_t_ptr", cast_uv_pipe_t_ptr_to_uv_stream_t_ptr},
        {"cast_uv_tcp_t_ptr_to_uv_stream_t_ptr", cast_uv_tcp_t_ptr_to_uv_stream_t_ptr},
        {"cast_uv_udp_t_ptr_to_uv_stream_t_ptr", cast_uv_udp_t_ptr_to_uv_stream_t_ptr},
        {"deref_sockaddr_in6_ptr", deref_sockaddr_in6_ptr},
        {"deref_sockaddr_in_ptr", deref_sockaddr_in_ptr},
        {"deref_uv_pipe_t_ptr", deref_uv_pipe_t_ptr},
        {"deref_uv_tcp_t_ptr", deref_uv_tcp_t_ptr},
        {"deref_uv_udp_t_ptr", deref_uv_udp_t_ptr},
        {"uv_accept", wrap_uv_accept},
        {"uv_ares_destroy", wrap_uv_ares_destroy},
        {"uv_ares_init_options", wrap_uv_ares_init_options},
        {"uv_async_init", wrap_uv_async_init},
        {"uv_async_send", wrap_uv_async_send},
        {"uv_buf_init", wrap_uv_buf_init},
        {"uv_check_init", wrap_uv_check_init},
        {"uv_check_start", wrap_uv_check_start},
        {"uv_check_stop", wrap_uv_check_stop},
        {"uv_cleanup", wrap_uv_cleanup},
        {"uv_close", wrap_uv_close},
        {"uv_default_loop", wrap_uv_default_loop},
        {"uv_err_name", wrap_uv_err_name},
        {"uv_exepath", wrap_uv_exepath},
        {"uv_fs_chmod", wrap_uv_fs_chmod},
        {"uv_fs_chown", wrap_uv_fs_chown},
        {"uv_fs_close", wrap_uv_fs_close},
        {"uv_fs_fchmod", wrap_uv_fs_fchmod},
        {"uv_fs_fchown", wrap_uv_fs_fchown},
        {"uv_fs_fdatasync", wrap_uv_fs_fdatasync},
        {"uv_fs_fstat", wrap_uv_fs_fstat},
        {"uv_fs_fsync", wrap_uv_fs_fsync},
        {"uv_fs_ftruncate", wrap_uv_fs_ftruncate},
        {"uv_fs_futime", wrap_uv_fs_futime},
        {"uv_fs_link", wrap_uv_fs_link},
        {"uv_fs_lstat", wrap_uv_fs_lstat},
        {"uv_fs_mkdir", wrap_uv_fs_mkdir},
        {"uv_fs_open", wrap_uv_fs_open},
        {"uv_fs_read", wrap_uv_fs_read},
        {"uv_fs_readdir", wrap_uv_fs_readdir},
        {"uv_fs_readlink", wrap_uv_fs_readlink},
        {"uv_fs_rename", wrap_uv_fs_rename},
        {"uv_fs_req_cleanup", wrap_uv_fs_req_cleanup},
        {"uv_fs_rmdir", wrap_uv_fs_rmdir},
        {"uv_fs_sendfile", wrap_uv_fs_sendfile},
        {"uv_fs_stat", wrap_uv_fs_stat},
        {"uv_fs_symlink", wrap_uv_fs_symlink},
        {"uv_fs_unlink", wrap_uv_fs_unlink},
        {"uv_fs_utime", wrap_uv_fs_utime},
        {"uv_fs_write", wrap_uv_fs_write},
        {"uv_getaddrinfo", wrap_uv_getaddrinfo},
        {"uv_hrtime", wrap_uv_hrtime},
        {"uv_idle_init", wrap_uv_idle_init},
        {"uv_idle_start", wrap_uv_idle_start},
        {"uv_idle_stop", wrap_uv_idle_stop},
        {"uv_ip4_addr", wrap_uv_ip4_addr},
        {"uv_ip4_name", wrap_uv_ip4_name},
        {"uv_ip6_addr", wrap_uv_ip6_addr},
        {"uv_ip6_name", wrap_uv_ip6_name},
        {"uv_is_active", wrap_uv_is_active},
        {"uv_is_tty", wrap_uv_is_tty},
        {"uv_last_error", wrap_uv_last_error},
        {"uv_listen", wrap_uv_listen},
        {"uv_loop_delete", wrap_uv_loop_delete},
        {"uv_loop_new", wrap_uv_loop_new},
        {"uv_now", wrap_uv_now},
        {"uv_pipe_bind", wrap_uv_pipe_bind},
        {"uv_pipe_connect", wrap_uv_pipe_connect},
        {"uv_pipe_init", wrap_uv_pipe_init},
        {"uv_pipe_open", wrap_uv_pipe_open},
        {"uv_prepare_init", wrap_uv_prepare_init},
        {"uv_prepare_start", wrap_uv_prepare_start},
        {"uv_prepare_stop", wrap_uv_prepare_stop},
        {"uv_process_kill", wrap_uv_process_kill},
        {"uv_queue_work", wrap_uv_queue_work},
        {"uv_read_start", wrap_uv_read_start},
        {"uv_read_stop", wrap_uv_read_stop},
        {"uv_ref", wrap_uv_ref},
        {"uv_run", wrap_uv_run},
        {"uv_shutdown", wrap_uv_shutdown},
        {"uv_spawn", wrap_uv_spawn},
        {"uv_std_handle", wrap_uv_std_handle},
        {"uv_strerror", wrap_uv_strerror},
        {"uv_tcp_bind", wrap_uv_tcp_bind},
        {"uv_tcp_bind6", wrap_uv_tcp_bind6},
        {"uv_tcp_connect", wrap_uv_tcp_connect},
        {"uv_tcp_connect6", wrap_uv_tcp_connect6},
        {"uv_tcp_getpeername", wrap_uv_tcp_getpeername},
        {"uv_tcp_getsockname", wrap_uv_tcp_getsockname},
        {"uv_tcp_init", wrap_uv_tcp_init},
        {"uv_timer_again", wrap_uv_timer_again},
        {"uv_timer_get_repeat", wrap_uv_timer_get_repeat},
        {"uv_timer_init", wrap_uv_timer_init},
        {"uv_timer_set_repeat", wrap_uv_timer_set_repeat},
        {"uv_timer_start", wrap_uv_timer_start},
        {"uv_timer_stop", wrap_uv_timer_stop},
        {"uv_tty_init", wrap_uv_tty_init},
        {"uv_tty_set_mode", wrap_uv_tty_set_mode},
        {"uv_udp_bind", wrap_uv_udp_bind},
        {"uv_udp_bind6", wrap_uv_udp_bind6},
        {"uv_udp_getsockname", wrap_uv_udp_getsockname},
        {"uv_udp_init", wrap_uv_udp_init},
        {"uv_udp_recv_start", wrap_uv_udp_recv_start},
        {"uv_udp_recv_stop", wrap_uv_udp_recv_stop},
        {"uv_unref", wrap_uv_unref},
        {"uv_update_time", wrap_uv_update_time},
        {"uv_write", wrap_uv_write},
        {NULL, NULL}
    };
    luaL_register(L, "uv_wrap", reg);

    lua_pushinteger(L, (lua_Integer) UV_UNKNOWN);
    lua_setfield(L, -2, "UV_UNKNOWN");

    lua_pushinteger(L, (lua_Integer) UV_OK);
    lua_setfield(L, -2, "UV_OK");

    lua_pushinteger(L, (lua_Integer) UV_EOF);
    lua_setfield(L, -2, "UV_EOF");

    lua_pushinteger(L, (lua_Integer) UV_EACCESS);
    lua_setfield(L, -2, "UV_EACCESS");

    lua_pushinteger(L, (lua_Integer) UV_EAGAIN);
    lua_setfield(L, -2, "UV_EAGAIN");

    lua_pushinteger(L, (lua_Integer) UV_EADDRINUSE);
    lua_setfield(L, -2, "UV_EADDRINUSE");

    lua_pushinteger(L, (lua_Integer) UV_EADDRNOTAVAIL);
    lua_setfield(L, -2, "UV_EADDRNOTAVAIL");

    lua_pushinteger(L, (lua_Integer) UV_EAFNOSUPPORT);
    lua_setfield(L, -2, "UV_EAFNOSUPPORT");

    lua_pushinteger(L, (lua_Integer) UV_EALREADY);
    lua_setfield(L, -2, "UV_EALREADY");

    lua_pushinteger(L, (lua_Integer) UV_EBADF);
    lua_setfield(L, -2, "UV_EBADF");

    lua_pushinteger(L, (lua_Integer) UV_EBUSY);
    lua_setfield(L, -2, "UV_EBUSY");

    lua_pushinteger(L, (lua_Integer) UV_ECONNABORTED);
    lua_setfield(L, -2, "UV_ECONNABORTED");

    lua_pushinteger(L, (lua_Integer) UV_ECONNREFUSED);
    lua_setfield(L, -2, "UV_ECONNREFUSED");

    lua_pushinteger(L, (lua_Integer) UV_ECONNRESET);
    lua_setfield(L, -2, "UV_ECONNRESET");

    lua_pushinteger(L, (lua_Integer) UV_EDESTADDRREQ);
    lua_setfield(L, -2, "UV_EDESTADDRREQ");

    lua_pushinteger(L, (lua_Integer) UV_EFAULT);
    lua_setfield(L, -2, "UV_EFAULT");

    lua_pushinteger(L, (lua_Integer) UV_EHOSTUNREACH);
    lua_setfield(L, -2, "UV_EHOSTUNREACH");

    lua_pushinteger(L, (lua_Integer) UV_EINTR);
    lua_setfield(L, -2, "UV_EINTR");

    lua_pushinteger(L, (lua_Integer) UV_EINVAL);
    lua_setfield(L, -2, "UV_EINVAL");

    lua_pushinteger(L, (lua_Integer) UV_EISCONN);
    lua_setfield(L, -2, "UV_EISCONN");

    lua_pushinteger(L, (lua_Integer) UV_EMFILE);
    lua_setfield(L, -2, "UV_EMFILE");

    lua_pushinteger(L, (lua_Integer) UV_EMSGSIZE);
    lua_setfield(L, -2, "UV_EMSGSIZE");

    lua_pushinteger(L, (lua_Integer) UV_ENETDOWN);
    lua_setfield(L, -2, "UV_ENETDOWN");

    lua_pushinteger(L, (lua_Integer) UV_ENETUNREACH);
    lua_setfield(L, -2, "UV_ENETUNREACH");

    lua_pushinteger(L, (lua_Integer) UV_ENFILE);
    lua_setfield(L, -2, "UV_ENFILE");

    lua_pushinteger(L, (lua_Integer) UV_ENOBUFS);
    lua_setfield(L, -2, "UV_ENOBUFS");

    lua_pushinteger(L, (lua_Integer) UV_ENOMEM);
    lua_setfield(L, -2, "UV_ENOMEM");

    lua_pushinteger(L, (lua_Integer) UV_ENONET);
    lua_setfield(L, -2, "UV_ENONET");

    lua_pushinteger(L, (lua_Integer) UV_ENOPROTOOPT);
    lua_setfield(L, -2, "UV_ENOPROTOOPT");

    lua_pushinteger(L, (lua_Integer) UV_ENOTCONN);
    lua_setfield(L, -2, "UV_ENOTCONN");

    lua_pushinteger(L, (lua_Integer) UV_ENOTSOCK);
    lua_setfield(L, -2, "UV_ENOTSOCK");

    lua_pushinteger(L, (lua_Integer) UV_ENOTSUP);
    lua_setfield(L, -2, "UV_ENOTSUP");

    lua_pushinteger(L, (lua_Integer) UV_ENOENT);
    lua_setfield(L, -2, "UV_ENOENT");

    lua_pushinteger(L, (lua_Integer) UV_EPIPE);
    lua_setfield(L, -2, "UV_EPIPE");

    lua_pushinteger(L, (lua_Integer) UV_EPROTO);
    lua_setfield(L, -2, "UV_EPROTO");

    lua_pushinteger(L, (lua_Integer) UV_EPROTONOSUPPORT);
    lua_setfield(L, -2, "UV_EPROTONOSUPPORT");

    lua_pushinteger(L, (lua_Integer) UV_EPROTOTYPE);
    lua_setfield(L, -2, "UV_EPROTOTYPE");

    lua_pushinteger(L, (lua_Integer) UV_ETIMEDOUT);
    lua_setfield(L, -2, "UV_ETIMEDOUT");

    lua_pushinteger(L, (lua_Integer) UV_ECHARSET);
    lua_setfield(L, -2, "UV_ECHARSET");

    lua_pushinteger(L, (lua_Integer) UV_EAIFAMNOSUPPORT);
    lua_setfield(L, -2, "UV_EAIFAMNOSUPPORT");

    lua_pushinteger(L, (lua_Integer) UV_EAINONAME);
    lua_setfield(L, -2, "UV_EAINONAME");

    lua_pushinteger(L, (lua_Integer) UV_EAISERVICE);
    lua_setfield(L, -2, "UV_EAISERVICE");

    lua_pushinteger(L, (lua_Integer) UV_EAISOCKTYPE);
    lua_setfield(L, -2, "UV_EAISOCKTYPE");

    lua_pushinteger(L, (lua_Integer) UV_ESHUTDOWN);
    lua_setfield(L, -2, "UV_ESHUTDOWN");

    lua_pushinteger(L, (lua_Integer) UV_EEXIST);
    lua_setfield(L, -2, "UV_EEXIST");

    lua_pushinteger(L, (lua_Integer) UV_FS_UNKNOWN);
    lua_setfield(L, -2, "UV_FS_UNKNOWN");

    lua_pushinteger(L, (lua_Integer) UV_FS_CUSTOM);
    lua_setfield(L, -2, "UV_FS_CUSTOM");

    lua_pushinteger(L, (lua_Integer) UV_FS_OPEN);
    lua_setfield(L, -2, "UV_FS_OPEN");

    lua_pushinteger(L, (lua_Integer) UV_FS_CLOSE);
    lua_setfield(L, -2, "UV_FS_CLOSE");

    lua_pushinteger(L, (lua_Integer) UV_FS_READ);
    lua_setfield(L, -2, "UV_FS_READ");

    lua_pushinteger(L, (lua_Integer) UV_FS_WRITE);
    lua_setfield(L, -2, "UV_FS_WRITE");

    lua_pushinteger(L, (lua_Integer) UV_FS_SENDFILE);
    lua_setfield(L, -2, "UV_FS_SENDFILE");

    lua_pushinteger(L, (lua_Integer) UV_FS_STAT);
    lua_setfield(L, -2, "UV_FS_STAT");

    lua_pushinteger(L, (lua_Integer) UV_FS_LSTAT);
    lua_setfield(L, -2, "UV_FS_LSTAT");

    lua_pushinteger(L, (lua_Integer) UV_FS_FSTAT);
    lua_setfield(L, -2, "UV_FS_FSTAT");

    lua_pushinteger(L, (lua_Integer) UV_FS_FTRUNCATE);
    lua_setfield(L, -2, "UV_FS_FTRUNCATE");

    lua_pushinteger(L, (lua_Integer) UV_FS_UTIME);
    lua_setfield(L, -2, "UV_FS_UTIME");

    lua_pushinteger(L, (lua_Integer) UV_FS_FUTIME);
    lua_setfield(L, -2, "UV_FS_FUTIME");

    lua_pushinteger(L, (lua_Integer) UV_FS_CHMOD);
    lua_setfield(L, -2, "UV_FS_CHMOD");

    lua_pushinteger(L, (lua_Integer) UV_FS_FCHMOD);
    lua_setfield(L, -2, "UV_FS_FCHMOD");

    lua_pushinteger(L, (lua_Integer) UV_FS_FSYNC);
    lua_setfield(L, -2, "UV_FS_FSYNC");

    lua_pushinteger(L, (lua_Integer) UV_FS_FDATASYNC);
    lua_setfield(L, -2, "UV_FS_FDATASYNC");

    lua_pushinteger(L, (lua_Integer) UV_FS_UNLINK);
    lua_setfield(L, -2, "UV_FS_UNLINK");

    lua_pushinteger(L, (lua_Integer) UV_FS_RMDIR);
    lua_setfield(L, -2, "UV_FS_RMDIR");

    lua_pushinteger(L, (lua_Integer) UV_FS_MKDIR);
    lua_setfield(L, -2, "UV_FS_MKDIR");

    lua_pushinteger(L, (lua_Integer) UV_FS_RENAME);
    lua_setfield(L, -2, "UV_FS_RENAME");

    lua_pushinteger(L, (lua_Integer) UV_FS_READDIR);
    lua_setfield(L, -2, "UV_FS_READDIR");

    lua_pushinteger(L, (lua_Integer) UV_FS_LINK);
    lua_setfield(L, -2, "UV_FS_LINK");

    lua_pushinteger(L, (lua_Integer) UV_FS_SYMLINK);
    lua_setfield(L, -2, "UV_FS_SYMLINK");

    lua_pushinteger(L, (lua_Integer) UV_FS_READLINK);
    lua_setfield(L, -2, "UV_FS_READLINK");

    lua_pushinteger(L, (lua_Integer) UV_FS_CHOWN);
    lua_setfield(L, -2, "UV_FS_CHOWN");

    lua_pushinteger(L, (lua_Integer) UV_FS_FCHOWN);
    lua_setfield(L, -2, "UV_FS_FCHOWN");

    lua_pushinteger(L, (lua_Integer) UV_UNKNOWN_HANDLE);
    lua_setfield(L, -2, "UV_UNKNOWN_HANDLE");

    lua_pushinteger(L, (lua_Integer) UV_TCP);
    lua_setfield(L, -2, "UV_TCP");

    lua_pushinteger(L, (lua_Integer) UV_UDP);
    lua_setfield(L, -2, "UV_UDP");

    lua_pushinteger(L, (lua_Integer) UV_NAMED_PIPE);
    lua_setfield(L, -2, "UV_NAMED_PIPE");

    lua_pushinteger(L, (lua_Integer) UV_TTY);
    lua_setfield(L, -2, "UV_TTY");

    lua_pushinteger(L, (lua_Integer) UV_FILE);
    lua_setfield(L, -2, "UV_FILE");

    lua_pushinteger(L, (lua_Integer) UV_TIMER);
    lua_setfield(L, -2, "UV_TIMER");

    lua_pushinteger(L, (lua_Integer) UV_PREPARE);
    lua_setfield(L, -2, "UV_PREPARE");

    lua_pushinteger(L, (lua_Integer) UV_CHECK);
    lua_setfield(L, -2, "UV_CHECK");

    lua_pushinteger(L, (lua_Integer) UV_IDLE);
    lua_setfield(L, -2, "UV_IDLE");

    lua_pushinteger(L, (lua_Integer) UV_ASYNC);
    lua_setfield(L, -2, "UV_ASYNC");

    lua_pushinteger(L, (lua_Integer) UV_ARES_TASK);
    lua_setfield(L, -2, "UV_ARES_TASK");

    lua_pushinteger(L, (lua_Integer) UV_ARES_EVENT);
    lua_setfield(L, -2, "UV_ARES_EVENT");

    lua_pushinteger(L, (lua_Integer) UV_PROCESS);
    lua_setfield(L, -2, "UV_PROCESS");

    lua_pushinteger(L, (lua_Integer) UV_UNKNOWN_REQ);
    lua_setfield(L, -2, "UV_UNKNOWN_REQ");

    lua_pushinteger(L, (lua_Integer) UV_CONNECT);
    lua_setfield(L, -2, "UV_CONNECT");

    lua_pushinteger(L, (lua_Integer) UV_ACCEPT);
    lua_setfield(L, -2, "UV_ACCEPT");

    lua_pushinteger(L, (lua_Integer) UV_READ);
    lua_setfield(L, -2, "UV_READ");

    lua_pushinteger(L, (lua_Integer) UV_WRITE);
    lua_setfield(L, -2, "UV_WRITE");

    lua_pushinteger(L, (lua_Integer) UV_SHUTDOWN);
    lua_setfield(L, -2, "UV_SHUTDOWN");

    lua_pushinteger(L, (lua_Integer) UV_WAKEUP);
    lua_setfield(L, -2, "UV_WAKEUP");

    lua_pushinteger(L, (lua_Integer) UV_UDP_SEND);
    lua_setfield(L, -2, "UV_UDP_SEND");

    lua_pushinteger(L, (lua_Integer) UV_FS);
    lua_setfield(L, -2, "UV_FS");

    lua_pushinteger(L, (lua_Integer) UV_WORK);
    lua_setfield(L, -2, "UV_WORK");

    lua_pushinteger(L, (lua_Integer) UV_GETADDRINFO);
    lua_setfield(L, -2, "UV_GETADDRINFO");

    lua_pushinteger(L, (lua_Integer) UV_REQ_TYPE_PRIVATE);
    lua_setfield(L, -2, "UV_REQ_TYPE_PRIVATE");

    lua_pushinteger(L, (lua_Integer) UV_STDIN);
    lua_setfield(L, -2, "UV_STDIN");

    lua_pushinteger(L, (lua_Integer) UV_STDOUT);
    lua_setfield(L, -2, "UV_STDOUT");

    lua_pushinteger(L, (lua_Integer) UV_STDERR);
    lua_setfield(L, -2, "UV_STDERR");

    lua_pushinteger(L, (lua_Integer) UV_UDP_IPV6ONLY);
    lua_setfield(L, -2, "UV_UDP_IPV6ONLY");

    lua_pushinteger(L, (lua_Integer) UV_UDP_PARTIAL);
    lua_setfield(L, -2, "UV_UDP_PARTIAL");

    return 1;
}
